import Head from "next/head";
import {
  Header,
  Explore,
  Work,
  Product,
  Projects,
  Connect,
  Github,
  Footer,
} from "../sections";

export default function Home() {
  return (
    <>
      <Head>
        <title>Meraj Portfolio :)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-icon.png" />
      </Head>

      <main className="bg-blue w-screen">
        <Header />
        <Explore />
        <Work />
        <Product />
        <Projects />
        <Connect />
        <Github />
        <Footer />
      </main>
    </>
  );
}
